[package]
name = "kaspa_signature_verification"
version = "0.1.0"
edition = "2024"

[dependencies]
bip39 = "1.2.0"
hex = "0.4.3"
kaspa-addresses = "0.15.0" 
kaspa-bip32 = "0.15.0"
secp256k1 = "0.26.0"
sha2 = "0.10.6"
rand = "0.8.5"
rand_core = "0.4"